export const games = [
   {
      nota: 10,
      nome: "Cyberpunk 2077",
      data: "19/mai/2024",
      genero: ["RPG", "Cyberpunk"],
      tempo: "169h 41m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co7497.webp",
   },
   {
      nota: 10,
      nome: "Elden Ring",
      data: "27/jun/2024",
      genero: ["Soulslike", "RPG"],
      tempo: "426h 41m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co4jni.webp",
   },
   {
      nota: 10,
      nome: "Dark Souls III",
      data: "11/ago/2024",
      genero: ["Soulslike"],
      tempo: "37h 53m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1vcf.webp",
   },
   {
      nota: 10,
      nome: "Silent Hill 2",
      data: "08/abr/2024",
      genero: ["Terror", "Atmosférico"],
      tempo: "8h 18m",
      versao: "PS2",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co5wkr.webp",
   },
   {
      nota: 10,
      nome: "Silent Hill f",
      data: "04/out/2025",
      genero: ["Terror", "Atmosférico"],
      tempo: "9h 41m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co9wy4.webp",
   },
   {
      nota: 10,
      nome: "Silent Hill 3",
      data: "23/abr/2024",
      genero: ["Terror"],
      tempo: "14h 05m",
      versao: "PS2",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co3kol.webp",
   },
   {
      nota: 9,
      nome: "Elden Ring Nightreign",
      data: "27/jun/2024",
      genero: ["Soulslike", "Co-op"],
      tempo: "42h 30m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co95gk.webp",
   },
   {
      nota: 9,
      nome: "Shadow of Memories",
      data: "19/jan/2025",
      genero: ["Atmosférico"],
      tempo: "7h 00m",
      versao: "PS2",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co53se.webp",
   },
   {
      nota: 9,
      nome: "Wuthering Waves",
      data: "24/mai/2025",
      genero: ["Gacha", "Aventura", "RPG", "Exploração"],
      tempo: "74h 00m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co92hl.webp",
   },
   {
      nota: 10,
      nome: "The Last of Us Remastered",
      data: "10/nov/2018",
      genero: ["Survival Horror", "Exploração", "Aventura"],
      tempo: "137h 24m",
      versao: "PS4",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co5zks.webp",
   },
   {
      nota: 10,
      nome: "The Last of Us Part II",
      data: "21/jun/2020",
      genero: ["Survival Horror", "Exploração", "Aventura"],
      tempo: "96h 30m",
      versao: "PS4",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co5ziw.webp",
   },
   {
      nota: 10,
      nome: "Death Stranding Director's Cut",
      data: "06/jul/2025",
      genero: ["Aventura", "Exploração", "Terror"],
      tempo: "35h 30m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co4rjc.webp",
   },
   {
      nota: 9,
      nome: "Resident Evil 7: Biohazard",
      data: "22/dez/2018",
      genero: ["Terror"],
      tempo: "25h 53m",
      versao: "PS4",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co8uu1.webp",
   },
   {
      nota: 9,
      nome: "Clair Obscur: Expedition 33",
      data: "07/ago/2025",
      genero: ["RPG", "Turno"],
      tempo: "20h 18m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co9gam.webp",
   },
   {
      nota: 9,
      nome: "Katana Zero",
      data: "28/jun/2022",
      genero: ["Plataforma", "Cyberpunk"],
      tempo: "5h 54m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1isp.webp",
   },
   {
      nota: 9,
      nome: "Stray",
      data: "21/jul/2022",
      genero: ["Atmosférico", "Cyberpunk"],
      tempo: "6h 24m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co4tt2.webp",
   },
   {
      nota: 9,
      nome: "Milk inside a bag of milk inside a bag of milk",
      data: "27/jan/2023",
      genero: ["Visual Novel", "Terror"],
      tempo: "0h 18m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co66n4.webp",
   },
   {
      nota: 9,
      nome: "Milk outside a bag of milk outside a bag of milk",
      data: "28/jan/2023",
      genero: ["Visual Novel", "Terror"],
      tempo: "3h 36m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co4bsi.webp",
   },
   {
      nota: 9,
      nome: "Doki Doki Literature Club",
      data: "31/jan/2023",
      genero: ["Visual Novel", "Terror"],
      tempo: "5h 42m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co6p5e.webp",
   },
   {
      nota: 9,
      nome: "Resident Evil 4",
      data: "05/abr/2023",
      genero: ["Survival Horror", "Terror"],
      tempo: "21h 18m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co20ci.webp",
   },
   {
      nota: 9,
      nome: "Resident Evil 4 (2023)",
      data: "08/abr/2023",
      genero: ["Survival Horror", "Terror"],
      tempo: "75h 05m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co6bo0.webp",
   },
   {
      nota: 9,
      nome: "Onimusha: Warlords",
      data: "09/mar/2024",
      genero: ["Hack and Slash"],
      tempo: "6h 47m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co4r26.webp",
   },
   {
      nota: 9,
      nome: "Heavy Rain",
      data: "08/jan/2025",
      genero: ["Filme Interativo", "Terror"],
      tempo: "10h 41m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co94lc.webp",
   },
   {
      nota: 8,
      nome: "Grand Theft Auto V",
      data: "21/dez/2018",
      genero: ["Mundo Aberto"],
      tempo: "66h 30m",
      versao: "PS4",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2lbd.webp",
   },
   {
      nota: 8,
      nome: "No, I'm Not A Human",
      data: "5/out/2025",
      genero: ["Terror", "Atmosférico"],
      tempo: "2h 21m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/coajvh.webp",
   },
   {
      nota: 8,
      nome: "ABZÛ",
      data: "20/jul/2025",
      genero: ["Aventura", "Exploração"],
      tempo: "1h 30m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co28sy.webp",
   },
   {
      nota: 8,
      nome: "Crash Bandicoot",
      data: "16/jul/2025",
      genero: ["Plataforma"],
      tempo: "4h 0m",
      versao: "PS1",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co555l.webp",
   },
   {
      nota: 8,
      nome: "Crash Bandicoot 2: Cortex Strikes Back",
      data: "17/jul/2025",
      genero: ["Plataforma"],
      tempo: "3h 0m",
      versao: "PS1",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co82vt.webp",
   },
   {
      nota: 7,
      nome: "Crash Bandicoot 3: Warped",
      data: "18/jul/2025",
      genero: ["Plataforma"],
      tempo: "3h 0m",
      versao: "PS1",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co873w.webp",
   },
   {
      nota: 8,
      nome: "Until Dawn",
      data: "23/dez/2018",
      genero: ["Filme Interativo", "Terror"],
      tempo: "8h 54m",
      versao: "PS4",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co9qxt.webp",
   },
   {
      nota: 8,
      nome: "Uncharted 4: A Thief's End",
      data: "27/abr/2019",
      genero: ["Exploração", "Aventura"],
      tempo: "24h 41m",
      versao: "PS4",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1r7h.webp",
   },
   {
      nota: 8,
      nome: "Naruto Shippuden: Ultimate Ninja Storm 3",
      data: "06/mai/2019",
      genero: ["Luta"],
      tempo: "17h 53m",
      versao: "PS4",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1ulj.webp",
   },
   {
      nota: 8,
      nome: "Naruto Shippuden: Ultimate Ninja Storm 4",
      data: "12/mai/2019",
      genero: ["Luta"],
      tempo: "38h 42m",
      versao: "PS4",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co3whm.webp",
   },
   {
      nota: 8,
      nome: "God of War",
      data: "23/jul/2019",
      genero: ["Aventura", "Exploração"],
      tempo: "34h 30m",
      versao: "PS4",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1tmu.webp",
   },
   {
      nota: 9,
      nome: "Katawa Shoujo",
      data: "08/jun/2025",
      genero: ["Visual Novel"],
      tempo: "11h 30m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co8kvi.webp",
   },
   {
      nota: 9,
      nome: "planetarian HD",
      data: "21/jun/2025",
      genero: ["Visual Novel"],
      tempo: "3h 50m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co24qe.webp",
   },
   {
      nota: 8,
      nome: "Resident Evil Village",
      data: "09/jun/2022",
      genero: ["Survival Horror", "Terror"],
      tempo: "12h 41m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2zpu.webp",
   },
   {
      nota: 8,
      nome: "Detroit: Become Human",
      data: "15/jun/2022",
      genero: ["Filme Interativo"],
      tempo: "14h 18m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co6mzf.webp",
   },
   {
      nota: 8,
      nome: "A Space for the Unbound",
      data: "20/jan/2023",
      genero: ["Atmosférico"],
      tempo: "11h 11m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co62kn.webp",
   },
   {
      nota: 8,
      nome: "REFLEXIA Prototype ver.",
      data: "30/jan/2023",
      genero: ["Visual Novel"],
      tempo: "1h 11m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co5qxb.webp",
   },
   {
      nota: 8,
      nome: "The Forest",
      data: "08/fev/2023",
      genero: ["Survival Horror", "Co-op", "Exploração"],
      tempo: "12h 54m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co20x5.webp",
   },
   {
      nota: 8,
      nome: "Undertale",
      data: "11/fev/2023",
      genero: ["RPG"],
      tempo: "11h 24m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2855.webp",
   },
   {
      nota: 8,
      nome: "Lucy: The Eternity She Wished For",
      data: "12/fev/2023",
      genero: ["Visual Novel"],
      tempo: "6h 12m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2ftq.webp",
   },
   {
      nota: 8,
      nome: "Little Nightmares",
      data: "14/fev/2023",
      genero: ["Terror"],
      tempo: "7h 42m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1rdi.webp",
   },
   {
      nota: 9,
      nome: "Little Nightmares II",
      data: "27/jul/2025",
      genero: ["Terror"],
      tempo: "5h 50m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/coa17l.webp",
   },
   {
      nota: 8,
      nome: "Sons Of The Forest",
      data: "27/fev/2023",
      genero: ["Survival Horror", "Terror", "Co-op", "Exploração"],
      tempo: "18h 41m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co67g5.webp",
   },
   {
      nota: 7,
      nome: "Selene ~Apoptosis~",
      data: "29/mar/2023",
      genero: ["Visual Novel"],
      tempo: "2h 47m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co66pt.webp",
   },
   {
      nota: 8,
      nome: "Resident Evil 2 (2019)",
      data: "09/abr/2023",
      genero: ["Survival Horror", "Terror"],
      tempo: "9h 35m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1ir3.webp",
   },
   {
      nota: 7,
      nome: "Threshold",
      data: "26/jun/2025",
      genero: ["Terror"],
      tempo: "1h 25m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co8coy.webp",
   },
   {
      nota: 8,
      nome: "Buckshot Roulette",
      data: "08/abr/2024",
      genero: ["Terror"],
      tempo: "9h 05m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co85h5.webp",
   },
   {
      nota: 8,
      nome: "Bayonetta",
      data: "07/mai/2024",
      genero: ["Hack and Slash"],
      tempo: "13h 35m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co8ngp.webp",
   },
   {
      nota: 8,
      nome: "Psychopomp",
      data: "01/jun/2024",
      genero: ["Terror"],
      tempo: "1h 23m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co7ozd.webp",
   },
   {
      nota: 8,
      nome: "Control",
      data: "03/jun/2024",
      genero: ["Terror"],
      tempo: "13h 35m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2evj.webp",
   },
   {
      nota: 8,
      nome: "Devil May Cry HD Collection",
      data: "09/jun/2024",
      genero: ["Hack and Slash"],
      tempo: "28h 00m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2n18.webp",
   },
   {
      nota: 8,
      nome: "Life is Strange",
      data: "22/jun/2024",
      genero: ["Filme Interativo"],
      tempo: "20h 23m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1r8e.webp",
   },
   {
      nota: 8,
      nome: "Lake Haven - Chrysalis",
      data: "15/out/2024",
      genero: ["Terror"],
      tempo: "1h 11m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co5i86.webp",
   },
   {
      nota: 7,
      nome: "Coralina",
      data: "23/fev/2023",
      genero: ["RPG", "Brasileiro"],
      tempo: "1h 15m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co5zhs.webp",
   },
   {
      nota: 7,
      nome: "Critters for Sale",
      data: "28/mar/2023",
      genero: ["Visual Novel"],
      tempo: "1h 16m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co45pg.webp",
   },
   {
      nota: 9,
      nome: "Resident Evil: Revelations",
      data: "24/nov/2024",
      genero: ["Survival Horror", "Terror"],
      tempo: "7h 35m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co8zvu.webp",
   },
   {
      nota: 8,
      nome: "Bad Parenting",
      data: "27/nov/2024",
      genero: ["Terror"],
      tempo: "0h 30m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co99t4.webp",
   },
   {
      nota: 8,
      nome: "[Bober Bros] The Hole",
      data: "08/dez/2024",
      genero: ["Terror"],
      tempo: "1h 06m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co8qyb.webp",
   },
   {
      nota: 8,
      nome: "Tekken 5 - Julia Chang",
      data: "15/jan/2025",
      genero: ["Luta"],
      tempo: "0h 28m",
      versao: "PS2",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co45jq.webp",
   },
   {
      nota: 7,
      nome: "Locke(d)",
      data: "08/mai/2025",
      genero: ["Visual Novel"],
      tempo: "0h 28m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co62h1.webp",
   },
   {
      nota: 8,
      nome: "Go! Go! Nippon! ~My First Trip to Japan~",
      data: "10/jul/2025",
      genero: ["Visual Novel"],
      tempo: "4h 50m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co41d5.webp",
   },
   {
      nota: 7,
      nome: "Stigmatized Property",
      data: "09/fev/2023",
      genero: ["Terror"],
      tempo: "4h 05m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co4248.webp",
   },
   {
      nota: 8,
      nome: "Coffee Talk",
      data: "18/fev/2023",
      genero: ["Visual Novel"],
      tempo: "8h 30m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co55rx.webp",
   },
   {
      nota: 8,
      nome: "Resident Evil 3 (2020)",
      data: "11/abr/2023",
      genero: ["Survival Horror", "Terror"],
      tempo: "6h 42m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co22l7.webp",
   },
   {
      nota: 7,
      nome: "The Town of Light",
      data: "27/mai/2023",
      genero: ["Terror"],
      tempo: "6h 47m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co20cu.webp",
   },
   {
      nota: 8,
      nome: "Resident Evil 6",
      data: "18/out/2023",
      genero: ["Survival Horror", "Co-op", "Terror"],
      tempo: "10h 41m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co3pyq.webp",
   },
   {
      nota: 7,
      nome: "Canine",
      data: "05/mar/2024",
      genero: ["Terror"],
      tempo: "0h 18m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co7tm6.webp",
   },
   {
      nota: 7,
      nome: "Looking Up I See Only A Ceiling",
      data: "10/mar/2024",
      genero: ["Visual Novel"],
      tempo: "4h 35m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co69l5.webp",
   },
   {
      nota: 7,
      nome: "The Room",
      data: "23/abr/2024",
      genero: ["Puzzle"],
      tempo: "2h 42m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co27bf.webp",
   },
   {
      nota: 7,
      nome: "心霊物件 | Haunted Property",
      data: "08/jun/2025",
      genero: ["Terror"],
      tempo: "1h 49m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co9jva.webp",
   },
   {
      nota: 7,
      nome: "The Coma 2: Vicious Sisters",
      data: "04/mai/2024",
      genero: ["Terror"],
      tempo: "7h 30m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1oew.webp",
   },
   {
      nota: 7,
      nome: "Firewatch",
      data: "06/jun/2024",
      genero: ["Atmosférico"],
      tempo: "8h 11m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1m35.webp",
   },
   {
      nota: 6,
      nome: "Bad End Theater",
      data: "14/mar/2024",
      genero: ["Visual Novel"],
      tempo: "1h 00m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co44y4.webp",
   },
   {
      nota: 8,
      nome: "Grizzly Man",
      data: "10/jun/2025",
      genero: ["Visual Novel", "Terror"],
      tempo: "1h 47m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co9y1s.webp",
   },
   {
      nota: 8,
      nome: "The NOexistenceN of you AND me",
      data: "11/jul/2025",
      genero: ["Visual Novel"],
      tempo: "1h 50m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co9apq.webp",
   },
   {
      nota: 6,
      nome: "Late Stops",
      data: "12/jul/2025",
      genero: ["Terror"],
      tempo: "0h 30m",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/coa3yc.webp",
   },
];

