export const games = [
    {
        nota: 10,
        nome: "Cyberpunk 2077",
        data: "19/mai/2024",
        genero: ["RPG"],
        tempo: "169h 41m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co7iy1.webp",
        review: 'Não sei nem por onde começar a falar, mas de algo tenho certeza: PODE COMPRAR sem medo, pois vale cada centavo.\n\nComecei a jogar Cyberpunk 2077 sem nenhuma expectativa, pois já estava com a ideia fixa de que o jogo não era bom, muito por causa do seu lançamento desastroso. Só que não esperava que esse mesmo jogo se tornaria o meu favorito! E, cara, como esse jogo é bom.\n\nÉ prazeroso passear por Night City. Tudo é muito lindo e bem feito. O jeito que projetaram a cidade me agradou demais: todas as construções, as tecnologias, as propagandas, cada detalhe te faz sentir o carinho que foi colocado nesse jogo. Nenhum outro jogo antes tinha me deixado tão fissurado quanto Cyberpunk. E olha que me apego muito a esse tipo de entretenimento, mas Cyberpunk é diferente... foi o único que me deu vontade de fazer cada serviço, cada missão secundária, tudo que aparece eu quero fazer. A história do jogo também é muito interessante, e as missões secundárias complementam bastante a experiência. Cada "arco" te prende de uma maneira que nem consigo descrever a perfeição que esse jogo é.\n\nSe você ainda está com preconceito e achando que o jogo é ruim, tente dar uma chance. Tenho certeza de que não irá se arrepender.\n\nRecomendo muito.',
    },
    {
        nota: 10,
        nome: "Elden Ring",
        data: "27/jun/2024",
        genero: ["Soulslike"],
        tempo: "426h 41m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co4jni.webp",
        review: "Esse jogo é simplesmente uma obra de arte. Todo o universo do jogo é fantástico, a jogabilidade dispensa comentários, e os gráficos, então, nem se fala. Parece que estou vendo uma pintura a cada momento. A FromSoftware é surreal. É realmente muito bom.\n\nOutra coisa é a sensação de recompensa que você sente após matar cada boss. Isso é bizarro! Nenhum outro jogo tinha me feito vibrar tanto ao conseguir matar um boss. É muito boa a sensação de superar o desafio, e tenho certeza de que quem jogou vai concordar comigo.\n\nFoi o meu primeiro Soulslike que zerei e recomendo demais!",
    },
    {
        nota: 10,
        nome: "Dark Souls III",
        data: "11/ago/2024",
        genero: ["Soulslike"],
        tempo: "37h 53m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1vcf.webp",
        review: "Jogaço! Após ter jogado Elden Ring, quis me aventurar na série Souls, e o que mais me chamava a atenção era Dark Souls III. Então, comecei a jogar e, cara, que jogo bom! É muito gostoso de jogar e progredir. Os gráficos são lindos, bem característicos da época. Dou 10/10, gostei muito.",
    },
    {
        nota: 10,
        nome: "Silent Hill 2",
        data: "08/abr/2024",
        genero: ["Terror", "Atmosférico"],
        tempo: "8h 18m",
        versao: "PS2",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co5wkr.webp",
    },
    {
        nota: 10,
        nome: "Silent Hill 3",
        data: "23/abr/2024",
        genero: ["Terror"],
        tempo: "14h 05m",
        versao: "PS2",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co3kol.webp",
    },
    {
        nota: 9,
        nome: "Elden Ring Nightreign",
        data: "27/jun/2024",
        genero: ["Soulslike"],
        tempo: "42h 30m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co95gk.webp",
        review: "O jogo é muito bom, estou me divertindo bastante com meu amigo, nem dá vontade de parar de jogar :D\n\nRecomendo demais! Os novos bosses estão muito legais também.\n\nO jogo tem sim suas falhas mas fico triste em ver as análises negativas reclamando de coisas que já tinham sido explicadas há muito tempo, não é nenhuma novidade.\n\nTenho certeza de que, se jogarem de cabeça fria/aberta, vão se divertir demais.\n\nTomara que a FromSoftware não deixe esse jogo de lado, pois vejo muito potencial nele.",
    },
    {
        nota: 9,
        nome: "Shadow of Memories",
        data: "19/jan/2025",
        genero: ["Atmosférico"],
        tempo: "7h 00m",
        versao: "PS2",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co53se.webp",
    },
    {
        nota: 9,
        nome: "Wuthering Waves",
        data: "24/mai/2025",
        genero: ["Gacha"],
        tempo: "74h 00m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co92hl.webp",
        review: "Muito bom! Gráfico lindo, design de personagens muito legal. Até o momento, parece ser bem safe para jogadores f2p, visto que já consegui diversos personagens com relativamente poucos tiros, mas pode ter sido sorte. As cutscenes são muito bonitas também.\n\nTá aprovado!",
    },
    {
        nota: 10,
        nome: "The Last of Us Remastered",
        data: "10/nov/2018",
        genero: ["Survival Horror"],
        tempo: "137h 24m",
        versao: "PS4",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co5zks.webp",
    },
    {
        nota: 10,
        nome: "The Last of Us Part II",
        data: "21/jun/2020",
        genero: ["Survival Horror"],
        tempo: "96h 30m",
        versao: "PS4",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co5ziw.webp",
    },
    {
        nota: 10,
        nome: "Death Stranding Director's Cut",
        data: "06/jul/2025",
        genero: ["Aventura", "Exploração", "Terror"],
        tempo: "35h 30m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co4rjc.webp",
    },
    {
        nota: 9,
        nome: "Resident Evil 7: Biohazard",
        data: "22/dez/2018",
        genero: ["Terror"],
        tempo: "25h 53m",
        versao: "PS4",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co8uu1.webp",
    },
    {
        nota: 9,
        nome: "Katana Zero",
        data: "28/jun/2022",
        genero: ["Plataforma"],
        tempo: "5h 54m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1isp.webp",
    },
    {
        nota: 9,
        nome: "Stray",
        data: "21/jul/2022",
        genero: ["Atmosférico"],
        tempo: "6h 24m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co4tt2.webp",
    },
    {
        nota: 9,
        nome: "Milk inside a bag of milk inside a bag of milk",
        data: "27/jan/2023",
        genero: ["Visual Novel"],
        tempo: "0h 18m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co66n4.webp",
    },
    {
        nota: 9,
        nome: "Milk outside a bag of milk outside a bag of milk",
        data: "28/jan/2023",
        genero: ["Visual Novel"],
        tempo: "3h 36m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co4bsi.webp",
    },
    {
        nota: 9,
        nome: "Doki Doki Literature Club",
        data: "31/jan/2023",
        genero: ["Visual Novel"],
        tempo: "5h 42m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co6p5e.webp",
    },
    {
        nota: 9,
        nome: "Resident Evil 4",
        data: "05/abr/2023",
        genero: ["Survival Horror"],
        tempo: "21h 18m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co20ci.webp",
    },
    {
        nota: 9,
        nome: "Resident Evil 4 (2023)",
        data: "08/abr/2023",
        genero: ["Survival Horror"],
        tempo: "75h 05m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co6bo0.webp",
    },
    {
        nota: 9,
        nome: "Onimusha: Warlords",
        data: "09/mar/2024",
        genero: ["Hack and Slash"],
        tempo: "6h 47m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co4r26.webp",
    },
    {
        nota: 9,
        nome: "Heavy Rain",
        data: "08/jan/2025",
        genero: ["Filme Interativo"],
        tempo: "10h 41m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co94lc.webp",
        review: "ABSOLUTE CINEMA. Cara, namoral, que jogo bom! A história é 10/10, cheia de plots interessantíssimos. Tive o prazer de jogar sem nenhum spoiler, e que experiência única! Simplesmente zerei em dois dias. No começo, achei que o jogo não ia me pegar tanto, mas eu não poderia estar mais errado. Que obra-prima!\n\nRecomendo demais, demais mesmo!",
    },
    {
        nota: 8,
        nome: "Grand Theft Auto V",
        data: "21/dez/2018",
        genero: ["Mundo Aberto"],
        tempo: "66h 30m",
        versao: "PS4",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2lbd.webp",
    },
    {
        nota: 8,
        nome: "ABZÛ",
        data: "20/jul/2025",
        genero: ["Aventura", "Exploração"],
        tempo: "1h 30m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co28sy.webp",
        review: "Simplesmente lindo!!!",
    },
    {
        nota: 8,
        nome: "Crash Bandicoot",
        data: "16/jul/2025",
        genero: ["Plataforma"],
        tempo: "4h 0m",
        versao: "PS1",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co555l.webp",
    },
    {
        nota: 8,
        nome: "Crash Bandicoot 2: Cortex Strikes Back",
        data: "17/jul/2025",
        genero: ["Plataforma"],
        tempo: "3h 0m",
        versao: "PS1",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co82vt.webp",
    },
    {
        nota: 7,
        nome: "Crash Bandicoot 3: Warped",
        data: "18/jul/2025",
        genero: ["Plataforma"],
        tempo: "3h 0m",
        versao: "PS1",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co873w.webp",
    },
    {
        nota: 8,
        nome: "Until Dawn",
        data: "23/dez/2018",
        genero: ["Filme Interativo"],
        tempo: "8h 54m",
        versao: "PS4",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co9qxt.webp",
    },
    {
        nota: 8,
        nome: "Uncharted 4: A Thief's End",
        data: "27/abr/2019",
        genero: ["Exploração", "Aventura"],
        tempo: "24h 41m",
        versao: "PS4",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1r7h.webp",
    },
    {
        nota: 8,
        nome: "Naruto Shippuden: Ultimate Ninja Storm 3",
        data: "06/mai/2019",
        genero: ["Luta"],
        tempo: "17h 53m",
        versao: "PS4",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1ulj.webp",
    },
    {
        nota: 8,
        nome: "Naruto Shippuden: Ultimate Ninja Storm 4",
        data: "12/mai/2019",
        genero: ["Luta"],
        tempo: "38h 42m",
        versao: "PS4",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co3whm.webp",
    },
    {
        nota: 8,
        nome: "God of War",
        data: "23/jul/2019",
        genero: ["Aventura"],
        tempo: "34h 30m",
        versao: "PS4",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1tmu.webp",
    },
    {
        nota: 9,
        nome: "Katawa Shoujo",
        data: "08/jun/2025",
        genero: ["Visual Novel"],
        tempo: "11h 30m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co8kvi.webp",
        review: "Tive que vir fazer essa análise. Por algum motivo, esse jogo me traz uma sensação de nostalgia, uma sensação de, sei lá... infância. Sabe aqueles dias em que você chegava da escola e não tinha nenhuma preocupação? Ou então um sábado em que passava o dia assistindo TV e comendo? É essa mesma vibe.\n\nA leitura é bem suave, a arte mt linda e trilha sonora mt boa.\n\nRecomendo!\n\nAtualização:\nFinalizei o jogo e continuo recomendando. Tudo o que falei anteriormente se aplica mais aos primeiros atos. Depois, ele ganha uma pegada um pouquinho diferente mas ainda muito boa. É de graça, vale a pena a experiência.",
    },
    {
        nota: 9,
        nome: "planetarian HD",
        data: "21/jun/2025",
        genero: ["Visual Novel"],
        tempo: "3h 50m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co24qe.webp",
        review: "Planetarian é uma obra-prima. Consegue te confortar mesmo em um cenário que abdicou desse sentimento. Muito bom mesmo, recomendo que joguem o quanto antes. Muito fofo e emocionante.",
    },
    {
        nota: 8,
        nome: "Resident Evil Village",
        data: "09/jun/2022",
        genero: ["Survival Horror"],
        tempo: "12h 41m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2zpu.webp",
    },
    {
        nota: 8,
        nome: "Detroit: Become Human",
        data: "15/jun/2022",
        genero: ["Filme Interativo"],
        tempo: "14h 18m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co6mzf.webp",
    },
    {
        nota: 8,
        nome: "A Space for the Unbound",
        data: "20/jan/2023",
        genero: ["Atmosférico"],
        tempo: "11h 11m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co62kn.webp",
    },
    {
        nota: 8,
        nome: "REFLEXIA Prototype ver.",
        data: "30/jan/2023",
        genero: ["Visual Novel"],
        tempo: "1h 11m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co5qxb.webp",
    },
    {
        nota: 8,
        nome: "The Forest",
        data: "08/fev/2023",
        genero: ["Survival Horror"],
        tempo: "12h 54m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co20x5.webp",
    },
    {
        nota: 8,
        nome: "Undertale",
        data: "11/fev/2023",
        genero: ["RPG"],
        tempo: "11h 24m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2855.webp",
    },
    {
        nota: 8,
        nome: "Lucy: The Eternity She Wished For",
        data: "12/fev/2023",
        genero: ["Visual Novel"],
        tempo: "6h 12m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2ftq.webp",
    },
    {
        nota: 8,
        nome: "Little Nightmares",
        data: "14/fev/2023",
        genero: ["Terror"],
        tempo: "7h 42m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1rdi.webp",
    },
    {
        nota: 9,
        nome: "Little Nightmares II",
        data: "27/jul/2025",
        genero: ["Terror"],
        tempo: "5h 50m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/coa17l.webp",
        review: "Muuuuuuito bom! Consegue ser ainda melhor que o primeiro, que já era perfeito.\n\nRecomendo demais, uma joia rara dos jogos de terror.\n\nPode ir sem medo!",
    },
    {
        nota: 8,
        nome: "Sons Of The Forest",
        data: "27/fev/2023",
        genero: ["Survival Horror"],
        tempo: "18h 41m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co67g5.webp",
    },
    {
        nota: 7,
        nome: "Selene ~Apoptosis~",
        data: "29/mar/2023",
        genero: ["Visual Novel"],
        tempo: "2h 47m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co66pt.webp",
    },
    {
        nota: 8,
        nome: "Resident Evil 2 (2019)",
        data: "09/abr/2023",
        genero: ["Survival Horror"],
        tempo: "9h 35m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1ir3.webp",
    },
    {
        nota: 7,
        nome: "Threshold",
        data: "26/jun/2025",
        genero: ["Terror"],
        tempo: "1h 25m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co8coy.webp",
        review: "Achei muito interessante!\n\nTinha visto a demo do jogo e me chamou bastante atenção. Apesar de curto, é muito bom, o universo do game me deixou bem curioso e instigou a descobrir mais.\n\nAs mecânicas são bem feitas e não ficam repetitivas. Conseguiram equilibrar bem a jogabilidade com os eventos do jogo.\n\nMas na minha opinião os finais deixaram a desejar, então recomendo mas em promoção.",
    },
    {
        nota: 8,
        nome: "Buckshot Roulette",
        data: "08/abr/2024",
        genero: ["Terror"],
        tempo: "9h 05m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co85h5.webp",
    },
    {
        nota: 8,
        nome: "Bayonetta",
        data: "07/mai/2024",
        genero: ["Hack and Slash"],
        tempo: "13h 35m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co8ngp.webp",
        review: "Muito bom\n\nNunca tinha jogado nenhum jogo da série Bayonetta, e, para ser sincero, nunca tinha visto nada sobre. Mas vi que estava em promoção e decidi me arriscar, e, cara, que jogo bom! Hack and slash de respeito, com gráficos lindos mesmo sendo 'antigo', design muito bem feito e história bem interessante. Recomendo muito. É uma pena que não tenha os outros Bayonetta para PC; se tivesse, com certeza eu jogaria.\n\nRecomendado.",
    },
    {
        nota: 8,
        nome: "Psychopomp",
        data: "01/jun/2024",
        genero: ["Terror"],
        tempo: "1h 23m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co7ozd.webp",
        review: "Recomendo\n\nEstilo de arte PSX, mecânicas bem feitas e divertidas. A protagonista me lembra um pouco a de Milk Inside a Bag of Milk Inside a Bag of Milk. O jogo é bem curtinho e vale a experiência. É de graça e está em português.",
    },
    {
        nota: 8,
        nome: "Control",
        data: "03/jun/2024",
        genero: ["Terror"],
        tempo: "13h 35m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2evj.webp",
    },
    {
        nota: 8,
        nome: "Devil May Cry HD Collection",
        data: "09/jun/2024",
        genero: ["Hack and Slash"],
        tempo: "28h 00m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2n18.webp",
        review: "Vou separar essa analise em três partes para os respectivos jogos.\n\nDMC 1:\nEsse foi o meu primeiro contato com a franquia. Não conhecia o jogo e só sabia que era uma das versões de Resident Evil 4 que foram feitas e acabou se tornando um jogo à parte.\n\nO jogo é muito bom. A história é simples de entender; nada é muito aprofundado nesse game. Dá para perceber algumas coisas que eles estavam testando, por assim dizer. O combate é bem divertido, mas muito desafiador. Posso dizer que, muitas vezes, é até desleal/desbalanceado, mas, com muita paciência, é possível zerar numa boa. Uma dica é: dê valor aos orbs.\n\nOs gráficos não me incomodam, pois gosto muito dos gráficos do PlayStation 2. Me dá nostalgia, e gosto muito de jogos dessa época e estética.\n\nUm bom jogo como introdução.\n\nDMC 2:\nBom, fui jogar com uma expectativa baixa, pois já tinha visto inúmeros relatos de que este seria o pior da série. Mas, por incrível que pareça, eu gostei. Há aspectos que realmente são inferiores, mas acabam compensando com as novas adições.\n\nOs gráficos não evoluíram muito do primeiro para o segundo, mas continuam bem bonitos, no clássico estilo do PlayStation 2. O combate é complicado, pois houve inovações nos movimentos em comparação com o primeiro jogo. Por exemplo, neste jogo há a opção de esquiva, enquanto no primeiro só era possível pular. Em compensação, os inimigos deste jogo parecem ser bem mais fáceis que os do anterior. Portanto, vai do gosto de cada um; eu gostei.\n\nA história seguiu a mesma linha do primeiro jogo também, nada muito aprofundado, apenas informações superficiais. Mesmo assim, ainda estou interessado em prosseguir.\n\nTambém recomendo este jogo.\n\nDMC 3:\nO salto dos primeiros jogos para o terceiro é absurdo. Se você, assim como eu, gostou dos anteriores, este aqui será um banquete.\n\nTudo nesse jogo é muito superior: o combate, a história, os chefes... tudo foi muito bem feito. Valeu a pena passar pelos outros jogos e poder experienciar a evolução discrepante. Gostei muito; a identidade criada nesse jogo foi excelente.\n\nOs gráficos não têm o que falar, são muito bonitos mesmo. Os modelos estão infinitamente superiores, muito lindos.\n\nRecomendo.",
    },
    {
        nota: 8,
        nome: "Life is Strange",
        data: "22/jun/2024",
        genero: ["Filme Interativo"],
        tempo: "20h 23m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1r8e.webp",
        review: "O jogo envelheceu bem, tem uma história legal, gráficos bonitos, trilha sonora muito boa e uma platina fácil para quem gosta de conquistas.\n\nRecomendo.",
    },
    {
        nota: 8,
        nome: "Lake Haven - Chrysalis",
        data: "15/out/2024",
        genero: ["Terror"],
        tempo: "1h 11m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co5i86.webp",
        review: "Uma linda homenagem aos jogos retrô, como Silent Hill e Resident Evil. Muito bom de verdade, com puzzles divertidos e uma estética que nem preciso mencionar... muito bem feita, realmente parece um jogo antigo. O criador está de parabéns, espero que lance mais jogos. Muito bom mesmo, recomendo!",
    },
    {
        nota: 7,
        nome: "Coralina",
        data: "23/fev/2023",
        genero: ["RPG"],
        tempo: "1h 15m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co5zhs.webp",
    },
    {
        nota: 7,
        nome: "Critters for Sale",
        data: "28/mar/2023",
        genero: ["RPG"],
        tempo: "1h 16m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co45pg.webp",
    },
    {
        nota: 9,
        nome: "Resident Evil: Revelations",
        data: "24/nov/2024",
        genero: ["Survival Horror"],
        tempo: "7h 35m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co8zvu.webp",
    },
    {
        nota: 8,
        nome: "Bad Parenting",
        data: "27/nov/2024",
        genero: ["Terror"],
        tempo: "0h 30m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co99t4.webp",
        review: "Jogo muito bom! Bem curto, mas consistente. A história é bem interessante, e os gráficos, junto com o filtro, combinaram bastante, dando a impressão de que estamos jogando um 'vídeo antigo' ou algo do gênero. Gostei muito!\n\nJá tinha jogado antes no Itch.io, e, quando vi que estava na Steam, comprei para apoiar. No aguardo de Bad Parenting 2!!!",
    },
    {
        nota: 8,
        nome: "[Bober Bros] The Hole",
        data: "08/dez/2024",
        genero: ["Terror"],
        tempo: "1h 06m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co8qyb.webp",
        review: "Jogo insano de terror psicológico, que aborda tópicos pesados. Estética impecável e aterrorizante. Recomendo demais!\n\nNo entanto, para quem é sensível a certos temas, é importante considerar com cuidado antes de jogar.",
    },
    {
        nota: 8,
        nome: "Tekken 5 - Julia Chang",
        data: "15/jan/2025",
        genero: ["Luta"],
        tempo: "0h 28m",
        versao: "PS2",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co45jq.webp",
    },
    {
        nota: 7,
        nome: "Locke(d)",
        data: "08/mai/2025",
        genero: ["Visual Novel"],
        tempo: "0h 28m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co62h1.webp",
    },
    {
        nota: 8,
        nome: "Go! Go! Nippon! ~My First Trip to Japan~",
        data: "10/jul/2025",
        genero: ["Visual Novel"],
        tempo: "4h 50m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co41d5.webp",
        review: "Muito interessante! É realmente uma viagem pelo Japão.\n\nSão mostrados vários lugares históricos e aspectos do seu passado. Recomendo!\n\nUma vn bem divertida.",
    },
    {
        nota: 7,
        nome: "Stigmatized Property",
        data: "09/fev/2023",
        genero: ["Terror"],
        tempo: "4h 05m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co4248.webp",
    },
    {
        nota: 8,
        nome: "Coffee Talk",
        data: "18/fev/2023",
        genero: ["Visual Novel"],
        tempo: "8h 30m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co55rx.webp",
    },
    {
        nota: 8,
        nome: "Resident Evil 3 (2020)",
        data: "11/abr/2023",
        genero: ["Survival Horror"],
        tempo: "6h 42m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co22l7.webp",
    },
    {
        nota: 7,
        nome: "The Town of Light",
        data: "27/mai/2023",
        genero: ["Terror"],
        tempo: "6h 47m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co20cu.webp",
    },
    {
        nota: 8,
        nome: "Resident Evil 6",
        data: "18/out/2023",
        genero: ["Survival Horror"],
        tempo: "10h 41m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co3pyq.webp",
    },
    {
        nota: 7,
        nome: "Canine",
        data: "05/mar/2024",
        genero: ["Terror"],
        tempo: "0h 18m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co7tm6.webp",
    },
    {
        nota: 7,
        nome: "Looking Up I See Only A Ceiling",
        data: "10/mar/2024",
        genero: ["Visual Novel"],
        tempo: "4h 35m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co69l5.webp",
    },
    {
        nota: 7,
        nome: "The Room",
        data: "23/abr/2024",
        genero: ["Puzzle"],
        tempo: "2h 42m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co27bf.webp",
    },
    {
        nota: 7,
        nome: "心霊物件 | Haunted Property",
        data: "08/jun/2025",
        genero: ["Terror"],
        tempo: "1h 49m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co9jva.webp",
        review: "Recomendo. Não espere nada extraordinário, é um jogo indie de terror, bem curtinho e simples, mas acho que pelo valor vale a pena. Para quem gosta de platinas, o jogo tem conquistas relativamente fáceis e é possível voltar nos capítulos jogados caso tenha deixado alguma conquista passar.",
    },
    {
        nota: 7,
        nome: "The Coma 2: Vicious Sisters",
        data: "04/mai/2024",
        genero: ["Terror"],
        tempo: "7h 30m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1oew.webp",
        review: "Jogo bom!\n\nParecia que eu estava jogando um manhwa. A arte desse jogo é linda e me agradou bastante. O jogo tem alguns 'puzzles', mas nada muito complicado, sendo interessante para o público mais casual. Dito isso, também há partes que serão um pouco desafiadoras, mas nada muito extremo, na dosagem perfeita para todos se divertirem.\n\nComo alguém que não jogou o primeiro jogo, até que não fiquei perdido na história. Dá para entender bem o que está acontecendo e especular algumas coisas. Claro que, se você tiver jogado o primeiro jogo, com certeza terá um melhor entendimento e imersão, mas não é necessariamente obrigatório para conseguir desfrutá-lo.\n\nRecomendo.",
    },
    {
        nota: 7,
        nome: "Firewatch",
        data: "06/jun/2024",
        genero: ["Atmosférico"],
        tempo: "8h 11m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1m35.webp",
        review: "Um bom jogo.\n\nNunca tinha visto nada sobre Firewatch, então joguei sem saber nada e foi muito bom. A narrativa é bem interessante e te deixa intrigado com os acontecimentos. Os gráficos do jogo são bem bonitos, com um estilo meio cartoonizado.\n\nVale muito a pena a experiência. Recomendo!",
    },
    {
        nota: 6,
        nome: "Bad End Theater",
        data: "14/mar/2024",
        genero: ["Visual Novel"],
        tempo: "1h 00m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co44y4.webp",
    },
    {
        nota: 8,
        nome: "Grizzly Man",
        data: "10/jun/2025",
        genero: ["Visual Novel"],
        tempo: "1h 47m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co9y1s.webp",
        review: "Muuuuuito bom! Fiquei até triste quando acabou, porque queria mais.\n\nQue jogo gostoso de jogar! Parece mesmo que a gente tá assistindo a um filme de thriller. Os personagens são bem legais, sem enrolação, pixel art lindíssima, trilha sonora combinou demais.\n\nInfelizmente não tem em português, mas não dá pra cobrar isso de um jogo indie. Muito bom mesmo, recomendo 10/10!",
    },
    {
        nota: 8,
        nome: "The NOexistenceN of you AND me",
        data: "11/jul/2025",
        genero: ["Visual Novel"],
        tempo: "1h 50m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co9apq.webp",
        review: "Esse jogo brinca com todos os conceitos e clichês das vn, além de trazer algumas reflexões filosóficas interessantes.\n\nÉ tão barato que chega a ser estranho ter tanta qualidade. Vale muito a pena aproveitar essa história.",
    },
    {
        nota: 6,
        nome: "Late Stops",
        data: "12/jul/2025",
        genero: ["Terror"],
        tempo: "0h 30m",
        versao: "PC",
        cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/coa3yc.webp",
    },
];
