export const wishlist = [
   {
      nome: "Silent Hill",
      genero: ["Horror"],
      tempo: "7h",
      versao: "PS1",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2vye.webp",
   },
   {
      nome: "Silent Hill 4: The Room",
      genero: ["Horror"],
      tempo: "10h",
      versao: "PS2",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2vyk.webp",
   },
   {
      nome: "Silent Hill: Origins",
      genero: ["Horror"],
      tempo: "8h",
      versao: "PS2",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2vyq.webp",
   },
   {
      nome: "Silent Hill: Shattered Memories",
      genero: ["Horror"],
      tempo: "7h",
      versao: "PS2",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2vyp.webp",
   },
   {
      nome: "Calling",
      genero: ["Horror"],
      tempo: "10h",
      versao: "Wii",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2wg7.webp",
   },
   {
      nome: "Your Turn to Die",
      genero: ["Visual Novel", "Horror"],
      tempo: "20h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co65s3.webp",
   },
   {
      nome: "AI Limit",
      genero: ["Souslike"],
      tempo: "18h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co8yk3.webp",
   },
   {
      nome: "Enigma of Fear",
      genero: ["Horror", "Survival Horror", "Puzzle"],
      tempo: "19h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co93ft.webp",
   },
   {
      nome: "Until Then",
      genero: ["Romance"],
      tempo: "18h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co7r5n.webp",
   },
   {
      nome: "Lost Records: Bloom & Rage",
      genero: ["Romance", "Puzzle"],
      tempo: "11h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co9p3a.webp",
   },
   {
      nome: "Tokyo Necro",
      genero: ["Cyberpunk", "Visual Novel"],
      tempo: "28h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co68za.webp",
   },
   {
      nome: "s.p.l.i.t",
      genero: ["Horror", "Puzzle"],
      tempo: "1h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/coa82q.webp",
   },
   {
      nome: "The House in Fata Morgana",
      genero: ["Terror", "Visual Novel"],
      tempo: "29h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co23cn.webp",
   },
   {
      nome: "Gore Screaming Show",
      genero: ["Terror", "Visual Novel", "Romance"],
      tempo: "7h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co5qao.webp",
   },
   {
      nome: "Wonderful Everyday - Down the Rabbit-Hole",
      genero: ["Terror", "Visual Novel", "Romance"],
      tempo: "38h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co3wbe.webp",
   },
   {
      nome: "YOU and ME and HER: A Love Story",
      genero: ["Terror", "Visual Novel", "Romance"],
      tempo: "9h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co45x8.webp",
   },
   {
      nome: "The 25th Ward: The Silver Case",
      genero: ["Puzzle", "Visual Novel"],
      tempo: "16h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co223e.webp",
   },
]
