export const wishlist = [
   {
      nome: "Silent Hill",
      genero: ["Horror"],
      tempo: "7h",
      versao: "PS1",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2vye.webp",
   },
   {
      nome: "Silent Hill 4: The Room",
      genero: ["Horror"],
      tempo: "10h",
      versao: "PS2",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2vyk.webp",
   },
   {
      nome: "Silent Hill: Origins",
      genero: ["Horror"],
      tempo: "8h",
      versao: "PS2",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2vyq.webp",
   },
   {
      nome: "Silent Hill: Shattered Memories",
      genero: ["Horror"],
      tempo: "7h",
      versao: "PS2",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2vyp.webp",
   },
   {
      nome: "Calling",
      genero: ["Horror"],
      tempo: "10h",
      versao: "Wii",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2wg7.webp",
   },
   {
      nome: "Your Turn to Die",
      genero: ["Visual Novel", "Horror"],
      tempo: "20h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co65s3.webp",
   },
   {
      nome: "AI Limit",
      genero: ["Souslike"],
      tempo: "18h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co8yk3.webp",
   },
   {
      nome: "Enigma of Fear",
      genero: ["Horror", "Survival Horror", "Puzzle"],
      tempo: "19h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co93ft.webp",
   },
   {
      nome: "Until Then",
      genero: ["Romance"],
      tempo: "18h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co7r5n.webp",
   },
   {
      nome: "Lost Records: Bloom & Rage",
      genero: ["Romance", "Puzzle"],
      tempo: "11h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co9p3a.webp",
   },
   {
      nome: "Tokyo Necro",
      genero: ["Cyberpunk", "Visual Novel"],
      tempo: "28h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co68za.webp",
   },
   {
      nome: "The House in Fata Morgana",
      genero: ["Horror", "Visual Novel"],
      tempo: "29h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co23cn.webp",
   },
   {
      nome: "Gore Screaming Show",
      genero: ["Horror", "Visual Novel", "Romance"],
      tempo: "7h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co5qao.webp",
   },
   {
      nome: "Wonderful Everyday - Down the Rabbit-Hole",
      genero: ["Horror", "Visual Novel", "Romance"],
      tempo: "38h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co3wbe.webp",
   },
   {
      nome: "YOU and ME and HER: A Love Story",
      genero: ["Horror", "Visual Novel", "Romance"],
      tempo: "9h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co45x8.webp",
   },
   {
      nome: "The 25th Ward: The Silver Case",
      genero: ["Puzzle", "Visual Novel"],
      tempo: "16h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co223e.webp",
   },
   {
      nome: "Mojika: Truth Rears Its Ugly Head",
      genero: ["Horror", "Visual Novel"],
      tempo: "4h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co8r1e.webp",
   },
   {
      nome: "Aokana: Four Rhythms Across the Blue",
      genero: ["Romance", "Visual Novel"],
      tempo: "24h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2t16.webp",
   },
   {
      nome: "Hanachirasu",
      genero: ["Ação", "Visual Novel"],
      tempo: "6h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2laa.webp",
   },
   {
      nome: "Fran Bow",
      genero: ["Horror", "2D"],
      tempo: "7h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co8lrn.webp",
   },
   {
      nome: "Gnosia",
      genero: ["Visual Novel"],
      tempo: "17h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co9458.webp",
   },
   {
      nome: "Chaos;Head",
      genero: ["Aventura", "Horror", "Visual Novel"],
      tempo: "22h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2hmm.webp",
   },
   {
      nome: "Chaos;Child",
      genero: ["Aventura", "Horror", "Visual Novel"],
      tempo: "31h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co26xc.webp",
   },
   {
      nome: "Kara no Shojo",
      genero: ["Horror", "Visual Novel"],
      tempo: "17h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2nrj.webp",
   },
   {
      nome: "Swan Song",
      genero: ["Horror", "Visual Novel"],
      tempo: "8h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co3dhg.jpg",
   },
   {
      nome: "GINKA",
      genero: ["Aventura", "Visual Novel"],
      tempo: "10h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co5zbr.webp",
   },
   {
      nome: "Witch on the Holy Night",
      genero: ["Aventura", "Visual Novel"],
      tempo: "24h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co5rw2.webp",
   },
   {
      nome: "Raging Loop",
      genero: ["Horror", "Puzzle", "Visual Novel"],
      tempo: "25h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co1tzv.webp",
   },
   {
      nome: "Spirit Hunter: Death Mark",
      genero: ["Horror", "Visual Novel"],
      tempo: "11h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2g1a.webp",
   },
   {
      nome: "Spirit Hunter: NG",
      genero: ["Horror", "Visual Novel"],
      tempo: "16h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2h6a.webp",
   },
   {
      nome: "Sayonara o Oshiete ~Comment te Dire Adieu~",
      genero: ["Horror", "Visual Novel"],
      tempo: "11h",
      versao: "PC",
      cover: "https://howlongtobeat.com/games/98457_Sayonara_o_Oshiete_Comment_te_Dire_Adieu.jpg?width=250",
   },
]
