export const wishlist = [
   {
      nome: "Silent Hill",
      genero: ["Terror"],
      tempo: "7h",
      versao: "PS1",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2vye.webp",
   },
   {
      nome: "Silent Hill 4: The Room",
      genero: ["Terror"],
      tempo: "10h",
      versao: "PS2",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2vyk.webp",
   },
   {
      nome: "Silent Hill: Origins",
      genero: ["Terror"],
      tempo: "8h",
      versao: "PS2",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2vyq.webp",
   },
   {
      nome: "Silent Hill: Shattered Memories",
      genero: ["Terror"],
      tempo: "7h",
      versao: "PS2",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2vyp.webp",
   },
   {
      nome: "Calling",
      genero: ["Terror"],
      tempo: "10h",
      versao: "Wii",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co2wg7.webp",
   },
   {
      nome: "Your Turn to Die",
      genero: ["Visual Novel", "Terror"],
      tempo: "20h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co65s3.webp",
   },
   {
      nome: "Saya no Uta",
      genero: ["Visual Novel", "Terror", "Romance"],
      tempo: "4h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co25zj.webp",
   },
   {
      nome: "Metaphor: ReFantazio",
      genero: ["RPG", "Turno"],
      tempo: "92h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co8d9t.webp",
   },
   {
      nome: "Persona 3 Reload",
      genero: ["RPG", "Turno"],
      tempo: "84h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co6z12.webp",
   },
   {
      nome: "Dead Space (2023)",
      genero: ["Terror", "Survival Horror"],
      tempo: "14h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co5esn.webp",
   },
   {
      nome: "Miside",
      genero: ["Terror", "Puzzle"],
      tempo: "4h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co7e6i.webp",
   },
   {
      nome: "AI Limit",
      genero: ["Souslike"],
      tempo: "18h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co8yk3.webp",
   },
   {
      nome: "Atomic Heart",
      genero: ["RPG"],
      tempo: "13h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co68ag.webp",
   },
   {
      nome: "The First Berserker: Khazan",
      genero: ["Souslike"],
      tempo: "35h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co8roc.webp",
   },
   {
      nome: "Enigma of Fear",
      genero: ["Terror", "Survival Horror", "Puzzle"],
      tempo: "19h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co93ft.webp",
   },
   {
      nome: "Until Then",
      genero: ["Romance"],
      tempo: "18h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co7r5n.webp",
   },
   {
      nome: "Lost Records: Bloom & Rage",
      genero: ["Romance", "Puzzle"],
      tempo: "11h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co9p3a.webp",
   },
   {
      nome: "Tokyo Necro",
      genero: ["Cyberpunk", "Visual Novel"],
      tempo: "28h",
      versao: "PC",
      cover: "https://images.igdb.com/igdb/image/upload/t_cover_big/co68za.webp",
   },
]
